### PR TITLE
Add environment data

### PR DESCRIPTION
**Pull request by georgf**
This adds file `environment.json` that we can fill manually with environment data points. I seeded it with the fields from `system.cpu` and `system.os`.
This is live for testing [here](http://georgf.github.io/temp-probe-dict/?search=system.&searchtype=in_any&optout=true&channel=release&constraint=is_in&version=any).

Some details:
- Allowed `revisions: {firstVersion: "42", ...` in the version range data, to make it easier to enter the data manually.
- Allowed for `revisions: {last: "latest"}`, so added data fields don't need manual updating.
- Added support for bug numbers already, because this actually helped me while adding this.
- Added `environment.json` to this repository, to support manually entered environment data.
- Added environment data `system.cpu.*` & `system.os.*` to `environment.json`.
- Dug out the history of these and filled in the correct versions and bug numbers.
- Added HTML escaping for descriptions because i ran into an unrelated bug with this.

### CODE REVIEW

**Comment by georgf** [comment]
You can see this live [here](http://georgf.github.io/temp-probe-dict/?search=system.&searchtype=in_any&optout=true&channel=release&constraint=is_in&version=any).

**Comment by georgf** [comment]
r=dexter mostly for:
- checking that the data is correct
- double-checking functionality

**Comment by georgf** [comment]
From conversations the "what dataset is this in" functionality will be useful to have live for feedback.
Pushing this live, but i'd still love to have feedback on it.

**Review by Dexterp37 — COMMENTED** [review]
This looks good to me, sorry for the delay! Just to be sure: is the json file built manually?

**Comment by georgf** [comment]
Yes, it is built manually for now, until we figure out how to deal with environment data in a declarative way.

**Pull request merged**
